In [1]:
import sbs_gob_pe_helper.VectorPrecioRentaFija as vp

✅ uc_driver ya está instalado.

In [2]:
df_emisores = vp.get_df_emisores()

In [3]:
df_emisores.head()

  cboEmisor           Emisor
0      9991       A&G Chavin
1      2011     ALICORP S.A.
2      9967    Atria Energía
3      0087  BANCO FALABELLA
4      0001             BCRP

In [4]:
df_precios = vp.get_precios_by_isin("PEP21400M064")

In [5]:
df_precios.head()

        Fecha Precio Limpio Precio Limpio (%) Precio Sucio    Tir
0  30/01/2025      1048.813           104.881     1050.369  5.021
1  29/01/2025      1048.727           104.873     1050.088  5.026
2  28/01/2025      1048.607           104.861     1049.773  5.033
3  27/01/2025      1048.732           104.873     1049.705  5.030
4  24/01/2025      1047.287           104.729     1047.676  5.093

### Emisor

El valor por defecto de este filtro es vacío, el cual hace que no se aplique este filtro.

| cboEmisor | Descripciòn |
| ------ | ------ |
|1000| GOB.CENTRAL|
|2011| ALICORP S.A.|
|0087| BANCO FALABELLA|
|0088| BCO RIPLEY|
|0001| BCRP|
|0011| CONTINENTAL|
|0042| CREDISCOTIA|
|0003| INTERBANK|

Los emisores disponibles se encuentran en la siguiente página: https://www.sbs.gob.pe/app/pu/CCID/Paginas/vp_rentafija.aspx

### Tipo de Moneda

El valor por defecto de este filtro es vacío, el cual hace que no se aplique este filtro.

| cboMoneda | Descripciòn |
| ------ | ------ |
| 1 |   Soles|
| 2 | Soles VAC|
| 3 | Dolares|

### Rating Emisión

El valor por defecto de este filtro es vacío, el cual hace que no se aplique este filtro.

| cboRating | 
| ------ | 
|A|
|A+|
|A-|
|AA|
|AA+|
|AA-|
|AAA|
|B-|
|BB|
|CP-1|
|CP-1+|
|CP-1-|
|CP-2|
|CP-2+|

In [6]:
fechaProceso = '21/07/2023'

df = vp.get_vector_precios(fechaProceso=fechaProceso)

In [7]:
df.head()

,Nemónico,ISIN/Identif.,Emisor,Moneda,P. Limpio (%),TIR %,Origen(*),Spreads,P. Limpio (monto),P. Sucio (monto),...,Cupón (%),Margen Libor (%),TIR % S/Opc,Rating Emisión,Ult. Cupón,Prox. Cupón,Duración,Var PLimpio,Var PSucio,Var Tir
0,CHAVI2CP2C,PEP20950V565,A&G Chavin,USD,99.899,6.268,Mercado,1.007,998.987,998.987,...,.000,.000,6.268,CP-2,28/10/2022,27/07/2023,.017,.013,.013,.198
1,CHAVI2CP2D,PEP20950V573,A&G Chavin,USD,99.304,6.320,Mercado,1.011,993.045,993.045,...,.000,.000,6.320,CP-2,30/11/2022,31/08/2023,.114,-.006,-.006,.210
2,CHAVI2CP2E,PEP20950V581,A&G Chavin,USD,98.466,6.380,Mercado,1.016,984.656,984.656,...,.000,.000,6.380,CP-2,20/01/2023,19/10/2023,.250,-.043,-.043,.254
3,CHAVI2CP2F,PEP20950V599,A&G Chavin,USD,96.309,6.468,Mercado,1.037,963.093,963.093,...,.000,.000,6.468,CP-2,29/05/2023,22/02/2024,.600,-.236,-.236,.447
4,CHAVI2CP3A,PEP20950V607,A&G Chavin,USD,95.491,6.297,Mercado,1.050,954.907,954.907,...,.000,.000,6.297,CP-2,21/07/2023,18/04/2024,.756,.000,.000,.000